openapi: 3.0.0
info:
  title: Travel API
  description: A simple travel API for destinations management
  version: 1.0.0
servers:
  - url: 'http://localhost:5001'
paths:
  /destinations:
    get:
      summary: Get all destinations
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
  /destinations/{id}:
    delete:
      summary: Delete a destination by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Destination deleted
        '404':
          description: Destination not found
components:
  schemas:
    Destination:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        location:
          type: string
        price_per_night:
          type: number
          format: float
